import type { RankDef, RankId, WeaponId } from "./types";

const UP_TO_AT4: WeaponId[] = ["m4", "m9", "m870", "mp5", "m249", "m110", "m24", "at4"];

export const RANKS: RankDef[] = [
  {
    id: "private",
    index: 0,
    code: "PVT",
    nameEn: "Private",
    nameZh: "二兵",
    chevrons: 1,
    needXp: 0,
    needMerit: 0,
    needDisc: 0,
    needMissions: 0,
    armor: 36,
    magBonus: 0,
    grenades: 0,
    command: 0,
    drone: false,
    fireSupport: false,
    commandCenter: false,
    range: false,
    weapons: ["m4", "m9", "m870"],
    privileges: ["基礎步槍與手槍", "跟隨班長執行命令", "標準頭盔與背心"],
  },
  {
    id: "pfc",
    index: 1,
    code: "PFC",
    nameEn: "Private First Class",
    nameZh: "一兵",
    chevrons: 2,
    needXp: 320,
    needMerit: 50,
    needDisc: 48,
    needMissions: 1,
    armor: 50,
    magBonus: 1,
    grenades: 2,
    command: 0,
    drone: false,
    fireSupport: false,
    commandCenter: false,
    range: true,
    weapons: ["m4", "m9", "m870", "mp5"],
    privileges: ["解鎖衝鋒槍", "手榴彈", "靶場訓練", "額外彈匣"],
  },
  {
    id: "specialist",
    index: 2,
    code: "SPC",
    nameEn: "Specialist",
    nameZh: "上等兵",
    chevrons: 3,
    needXp: 780,
    needMerit: 140,
    needDisc: 52,
    needMissions: 3,
    armor: 64,
    magBonus: 2,
    grenades: 3,
    command: 0,
    drone: false,
    fireSupport: false,
    commandCenter: false,
    range: true,
    weapons: ["m4", "m9", "m870", "mp5", "m249"],
    privileges: ["解鎖機槍", "選擇專長", "強化防彈衣", "火力手／醫護"],
  },
  {
    id: "corporal",
    index: 3,
    code: "CPL",
    nameEn: "Corporal",
    nameZh: "下士",
    chevrons: 4,
    needXp: 1500,
    needMerit: 260,
    needDisc: 56,
    needMissions: 5,
    armor: 76,
    magBonus: 2,
    grenades: 3,
    command: 2,
    drone: false,
    fireSupport: false,
    commandCenter: false,
    range: true,
    weapons: ["m4", "m9", "m870", "mp5", "m249", "m110"],
    privileges: ["指揮 2 名隊友", "跟隨／防守／攻擊命令", "精確射手步槍", "無線電"],
  },
  {
    id: "sergeant",
    index: 4,
    code: "SGT",
    nameEn: "Sergeant",
    nameZh: "中士",
    chevrons: 5,
    needXp: 2500,
    needMerit: 420,
    needDisc: 60,
    needMissions: 8,
    armor: 88,
    magBonus: 3,
    grenades: 4,
    command: 4,
    drone: true,
    fireSupport: false,
    commandCenter: false,
    range: true,
    weapons: ["m4", "m9", "m870", "mp5", "m249", "m110", "m24"],
    privileges: ["完整小隊指揮", "無人機偵察", "狙擊步槍", "隊友稱呼班長"],
  },
  {
    id: "lieutenant",
    index: 5,
    code: "2LT",
    nameEn: "Second Lieutenant",
    nameZh: "少尉",
    chevrons: 1,
    needXp: 3900,
    needMerit: 640,
    needDisc: 64,
    needMissions: 11,
    armor: 100,
    magBonus: 3,
    grenades: 4,
    command: 4,
    drone: true,
    fireSupport: true,
    commandCenter: true,
    range: true,
    weapons: UP_TO_AT4,
    privileges: ["排級火力支援", "反裝甲武器", "指揮中心權限", "戰術標記"],
  },
  {
    id: "firstLieutenant",
    index: 6,
    code: "1LT",
    nameEn: "First Lieutenant",
    nameZh: "中尉",
    chevrons: 2,
    needXp: 5600,
    needMerit: 900,
    needDisc: 66,
    needMissions: 15,
    armor: 108,
    magBonus: 4,
    grenades: 5,
    command: 5,
    drone: true,
    fireSupport: true,
    commandCenter: true,
    range: true,
    weapons: [...UP_TO_AT4, "m320"],
    privileges: ["指揮 5 人", "M320 榴彈發射器", "三輪彈著火力", "無人機時間延長"],
  },
  {
    id: "captain",
    index: 7,
    code: "CPT",
    nameEn: "Captain",
    nameZh: "上尉",
    chevrons: 3,
    needXp: 7800,
    needMerit: 1220,
    needDisc: 68,
    needMissions: 20,
    armor: 116,
    magBonus: 4,
    grenades: 5,
    command: 5,
    drone: true,
    fireSupport: true,
    commandCenter: true,
    range: true,
    weapons: [...UP_TO_AT4, "m320", "scar"],
    privileges: ["連級火力、冷卻縮短", "SCAR-H 戰鬥步槍", "隊友稱呼連長", "更厚的裝甲"],
  },
  {
    id: "major",
    index: 8,
    code: "MAJ",
    nameEn: "Major",
    nameZh: "少校",
    chevrons: 4,
    needXp: 10500,
    needMerit: 1600,
    needDisc: 70,
    needMissions: 26,
    armor: 128,
    magBonus: 5,
    grenades: 6,
    command: 6,
    drone: true,
    fireSupport: true,
    commandCenter: true,
    range: true,
    weapons: [...UP_TO_AT4, "m320", "scar", "javelin"],
    privileges: ["營級火力", "標槍飛彈", "6 人小隊", "最短支援冷卻"],
  },
];

export const RANK_BY_ID: Record<RankId, RankDef> = Object.fromEntries(
  RANKS.map((r) => [r.id, r]),
) as Record<RankId, RankDef>;

export function rankById(id: RankId): RankDef {
  return RANK_BY_ID[id] ?? RANK_BY_ID.private;
}

export function nextRank(id: RankId): RankDef | null {
  const r = rankById(id);
  return RANKS[r.index + 1] ?? null;
}

export function canPromote(
  id: RankId,
  xp: number,
  merit: number,
  disc: number,
  missions: number,
): RankDef | null {
  const n = nextRank(id);
  if (!n) return null;
  if (xp < n.needXp || merit < n.needMerit || disc < n.needDisc || missions < n.needMissions) {
    return null;
  }
  return n;
}

export function isOfficer(id: RankId): boolean {
  return rankById(id).index >= 5;
}
