import type { WeaponDef, WeaponId } from "./types";

export const WEAPONS: WeaponDef[] = [
  {
    id: "m4",
    name: "M4A1",
    className: "突擊步槍",
    damage: 24,
    pellets: 1,
    rpm: 720,
    mag: 30,
    reserve: 150,
    range: 560,
    spread: 0.038,
    recoil: 0.32,
    accuracy: 0.84,
    speed: 980,
    reload: 1.55,
    explosive: false,
    blast: 0,
    rank: "private",
  },
  {
    id: "mp5",
    name: "MP5",
    className: "衝鋒槍",
    damage: 16,
    pellets: 1,
    rpm: 820,
    mag: 30,
    reserve: 180,
    range: 280,
    spread: 0.055,
    recoil: 0.18,
    accuracy: 0.76,
    speed: 860,
    reload: 1.35,
    explosive: false,
    blast: 0,
    rank: "pfc",
  },
  {
    id: "m870",
    name: "M870",
    className: "霰彈槍",
    damage: 11,
    pellets: 7,
    rpm: 68,
    mag: 8,
    reserve: 32,
    range: 160,
    spread: 0.16,
    recoil: 0.72,
    accuracy: 0.42,
    speed: 780,
    reload: 2.4,
    explosive: false,
    blast: 0,
    rank: "private",
  },
  {
    id: "m9",
    name: "M9",
    className: "手槍",
    damage: 20,
    pellets: 1,
    rpm: 260,
    mag: 15,
    reserve: 60,
    range: 200,
    spread: 0.05,
    recoil: 0.2,
    accuracy: 0.7,
    speed: 820,
    reload: 1.2,
    explosive: false,
    blast: 0,
    rank: "private",
  },
  {
    id: "m249",
    name: "M249",
    className: "機槍",
    damage: 28,
    pellets: 1,
    rpm: 740,
    mag: 100,
    reserve: 200,
    range: 620,
    spread: 0.06,
    recoil: 0.48,
    accuracy: 0.7,
    speed: 940,
    reload: 3.4,
    explosive: false,
    blast: 0,
    rank: "specialist",
  },
  {
    id: "m110",
    name: "M110",
    className: "精確射手步槍",
    damage: 52,
    pellets: 1,
    rpm: 210,
    mag: 20,
    reserve: 80,
    range: 860,
    spread: 0.012,
    recoil: 0.4,
    accuracy: 0.94,
    speed: 1180,
    reload: 2.1,
    explosive: false,
    blast: 0,
    rank: "corporal",
  },
  {
    id: "m24",
    name: "M24",
    className: "狙擊步槍",
    damage: 92,
    pellets: 1,
    rpm: 42,
    mag: 5,
    reserve: 25,
    range: 1100,
    spread: 0.006,
    recoil: 0.62,
    accuracy: 0.97,
    speed: 1320,
    reload: 2.6,
    explosive: false,
    blast: 0,
    rank: "sergeant",
  },
  {
    id: "at4",
    name: "AT4",
    className: "反裝甲",
    damage: 160,
    pellets: 1,
    rpm: 10,
    mag: 1,
    reserve: 3,
    range: 480,
    spread: 0.02,
    recoil: 0.9,
    accuracy: 0.62,
    speed: 620,
    reload: 3.8,
    explosive: true,
    blast: 110,
    rank: "lieutenant",
  },
  {
    id: "m320",
    name: "M320",
    className: "榴彈發射器",
    damage: 78,
    pellets: 1,
    rpm: 28,
    mag: 6,
    reserve: 18,
    range: 420,
    spread: 0.03,
    recoil: 0.55,
    accuracy: 0.68,
    speed: 420,
    reload: 2.8,
    explosive: true,
    blast: 86,
    rank: "firstLieutenant",
  },
  {
    id: "scar",
    name: "SCAR-H",
    className: "戰鬥步槍",
    damage: 36,
    pellets: 1,
    rpm: 600,
    mag: 20,
    reserve: 100,
    range: 720,
    spread: 0.022,
    recoil: 0.38,
    accuracy: 0.9,
    speed: 1080,
    reload: 1.85,
    explosive: false,
    blast: 0,
    rank: "captain",
  },
  {
    id: "javelin",
    name: "FGM-148",
    className: "標槍飛彈",
    damage: 240,
    pellets: 1,
    rpm: 8,
    mag: 1,
    reserve: 4,
    range: 720,
    spread: 0.01,
    recoil: 1,
    accuracy: 0.78,
    speed: 480,
    reload: 4.2,
    explosive: true,
    blast: 150,
    rank: "major",
  },
];

export const WEAPON_BY_ID: Record<WeaponId, WeaponDef> = Object.fromEntries(
  WEAPONS.map((w) => [w.id, w]),
) as Record<WeaponId, WeaponDef>;

export function weaponById(id: WeaponId): WeaponDef {
  return WEAPON_BY_ID[id];
}
